### ISSUE TITLE
ConfigTool not saving VersionOne connection parameters

### ISSUE THREAD

**Issue by mirvin** [versionone/VersionOne.Integration.HPALM#1]
## Problem
This occurs when needing to save a V1/QC configuration where the VersionOne server instance uses WIA.

Given a user checks the "Use Windows Integrated Authentication" checkbox,
And enters a username/password
And saves the configuration,
When the user re-opens the configtool,
Then the username and password is blank.

In general, when using WIA, the default behavior is to leave the username & password blank. In the case we have have the need to specify a different user than the one logged into particular machine on a domain, we have to explicitly state a user (fully qualified Domain & user) and password in addition to the URL. The later case is the culprit.

## Reproduce
1. Start ServiceHostConfigtool.exe
2. On the General tab, click "Use Windows Integrated Authentication"
3. Enter Server URL
4. Enter Username and password
5. Click File->Save  to save the file
6. Reopen configtool
7. Observe the empty Username and password

**Comment by aceybunch** [comment]
Fixed in 8.4.0.0 release.
