### ISSUE TITLE
ConfigTool will not validate using correct WIA credentials

### ISSUE THREAD

**Issue by mirvin** [versionone/VersionOne.Integration.HPALM#2]
## Problem
This occurs when user needs to validate a V1/QC configuration where the VersionOne server instance uses WIA. 

Given a user checks the "Use Windows Integrated Authentication" checkbox,
And enters an explicit username and password
When the user clicks "Validate",
Then the user gets "Validation failed..." message.

The proof that the connection parameters are all correct and can connect to VersionOne is that when the configuration is saved in spite of the failed validation and when the integration is started, it validates properly by passing the initial diagnostics testing done by the integration prior to entering the main event loop.

## Reproduce:
1. Start ServiceHostConfigtool.exe
2. On the General tab, click "Use Windows Integrated Authentication"
3. Enter Server URL
4. Enter Username and password
5. Click validate
6. Observe the failure (see attachment)
7. Save the configuration file
8. Execute VersionOne.ServiceHost.exe 
9. Observe a successful connection to VersionOne (See second diagram)

![12-13-2013 12-13-43 pm](https://f.cloud.github.com/assets/259870/1744288/47bd5a4c-641a-11e3-9807-4c6bb2dc32b6.png)

![second](https://f.cloud.github.com/assets/259870/1745176/fcdf3314-6429-11e3-9f57-d8dacda22657.png)

**Comment by aceybunch** [comment]
Fixed in 8.4.0.0 release.
